### PR TITLE
docs: add flagd to the general documentation page

### PR DESCRIPTION
**Pull request by aepfli**
Added flagd via dropdown to the official documentation page, like we already did with community etc.

### CODE REVIEW

**Comment by aepfli** [comment]
created a suggestion pr for htmltest - to handle  this issue with the dropdown - https://github.com/wjdp/htmltest/pull/213

**Comment by beeme1mr** [comment]
Hey @aepfli, I talked to the GC about this last week. We think that it would make sense to create another top-level category called "Ecosystem". This would be an ideal place to put documentation for OpenFeature Operator, Flagd, and supported vendors.

I've put together an extremely high-level mock to try and move the discussion along.

image

I can help with the copy. Adding the vendors can be handled in a separate issue.

FYI, @open-feature/governance-board

**Comment by aepfli** [comment]
I looked, and it seems like it is more challenging than we would like to have multi-instance docs within the sidebar. Whereas within the navbar, it is easy.

Additional remark, within the navbar, we can only have one level of navigation, so my suggestion would be something like
image

It is a compromise between both approaches, what do you think?

**Comment by beeme1mr** [comment]
I've created an issue to create an ecosystem page. I think we can explore this PR again once that page is available.

https://github.com/open-feature/docs.openfeature.dev/issues/329

**Pull request closed without merging**
