### PR TITLE
feat: theme switcher

### LINKED ISSUE #85: Swizzle the light/dark theme switcher to look like the OpenFeature toggle
See: https://docusaurus.io/docs/swizzling

### PR DESCRIPTION
**Pull request by skyerus**
## This PR

Swizzle the light/dark theme switcher to look like the OpenFeature toggle

### Related Issues

Fixes #85

### CODE REVIEW

**Comment by toddbaert** [comment]
This is AWESOME. Nice work.

**Review by toddbaert — APPROVED** [review]

**Comment by toddbaert** [comment]
I found one TINY bug which won't stop me from approving, but if it's easy you may want to address it:

If the page is loaded initially in dark mode, the toggle's initial position isn't correct, which looks a bit weird the first toggle.

**Comment by toddbaert** [comment]
If I set it to dark, then reload the page, that's when I see the issue:

https://user-images.githubusercontent.com/25272906/198368871-5d693239-343a-47dc-8631-8f3a16138d17.mp4

**Comment by skyerus** [comment]
@toddbaert I've tried to reproduce this on chrome, safari and firefox to no avail. My best guess is that for some reason this scss rule isn't applying:
```
&.isDarkMode {
    .toggleIcon {
      .track {
        div {
          right: 15px;
        }
      }
    }
  }
```
as from the screenshot it looks like it's in the correct state except the inner dark circle ought to be positioned to the left.
Not sure how practical me trying to fix this would be without feedback.

**Comment by toddbaert** [comment]
@skyerus ok if you can't reproduce it, it might just be my chrome version or something else weird. This is a great change anyway so I'll just merge, and maybe investigate on my end.

Thanks again for doing it, it's a great little tweak. I hope you enjoyed the UI work.

**Pull request merged**
