### PR TITLE
Add JS Split provider

### PR DESCRIPTION
**Pull request by joshsirota**
Add JS frontend Split provider

### CODE REVIEW

**Comment by beeme1mr** [comment]
Hey @joshsirota, it looks like the build is failing because the Split logo wasn't imported. Could you please do that and sign-off your commits? Thanks!

https://github.com/open-feature/docs.openfeature.dev/pull/186/checks?check_run_id=9604393229

**Comment by joshsirota** [comment]
Fixed @beeme1mr, thanks!

**Comment by joshsirota** [comment]
Hey @beeme1mr, while trying to fix my missing DCO signoffs, I somehow ended up with an extra commit in this branch with a change to package.json. I didn't mean to change that. Can you resolve the conflict and ignore that? There's probably a way for me to fix it but I don't want to mess this up even more.

**Comment by beeme1mr** [comment]
Sure @joshsirota, I've opened up a separate PR that includes the changes.

https://github.com/open-feature/docs.openfeature.dev/pull/201

**Pull request closed without merging**
