### PR TITLE
add split java provider

### PR DESCRIPTION
**Pull request by beeme1mr**
This PR adds the Split Java provider. It's currently a draft because the repo is private.

Direct link: https://deploy-preview-98--lucky-creponne-baf9b3.netlify.app/docs/reference/technologies/java/

### CODE REVIEW

**Comment by beeme1mr** [comment]
@patricioe I converted the available Split marketing assets to an SVG and used only the logo (without the text). Are you okay with this approach or do you have an official SVG we can use?

**Review by toddbaert — APPROVED** [review]

**Comment by toddbaert** [comment]
I rebased this on main to make sure it was working with other changes.

> @patricioe I converted the available Split marketing assets to an SVG and used only the logo (without the text). Are you okay with this approach or do you have an official SVG we can use?

I think this looks much better than the text logo, just my opinion though!

**Comment by patricioe** [comment]
@beeme1mr @toddbaert thank you. All good.

Are you waiting for the repo to be public? we can switch it on today.

**Comment by beeme1mr** [comment]
Hey @patricioe, I just need the link to go to a place with some basic documentation. Making the repo public and having a readme would be great but any other form of documentation would work too.

**Comment by patricioe** [comment]
@beeme1mr @toddbaert repo is public. We should be good to go. Take a look at the README we added.

**Review by patricioe — APPROVED** [review]

**Review by rgrassian-split — APPROVED** [review]

**Comment by beeme1mr** [comment]
Hi @patricioe and @rgrassian-split, amazing job with the readme! Thanks for your contributions.

**Pull request merged**
